### ISSUE TITLE
安装不了easyutils 

### ISSUE THREAD

**Issue by chenyangguang** [shidenggui/easyutils#2]
_终端执行 
 sudo pip install easyutils
然后报这个_
Downloading/unpacking easyutils
  Downloading easyutils-0.0.2.tar.gz
  Running setup.py (path:/tmp/pip_build_root/easyutils/setup.py) egg_info for package easyutils
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_root/easyutils/setup.py", line 3, in <module>
        import easyutils
      File "easyutils/**init**.py", line 1, in <module>
        from . import stock
      File "easyutils/stock.py", line 7
    SyntaxError: Non-ASCII character '\xe5' in file easyutils/stock.py on line 7, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_root/easyutils/setup.py", line 3, in <module>

```
import easyutils
```

  File "easyutils/**init**.py", line 1, in <module>

```
from . import stock
```

  File "easyutils/stock.py", line 7

SyntaxError: Non-ASCII character '\xe5' in file easyutils/stock.py on line 7, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details

我一愣，跑去 安装stock 
➜  web-scraper git:(master) ✗ sudo pip install stock
Downloading/unpacking stock
  Downloading stock-0.8.tar.gz
  Running setup.py (path:/tmp/pip_build_root/stock/setup.py) egg_info for package stock

```
file stock.py (for module stock) not found
warning: no files found matching 'test_requirements.txt'
```

Downloading/unpacking flask (from stock)
  Downloading Flask-0.11.1-py2.py3-none-any.whl (80kB): 0bytes downloaded
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1198, in prepare_files
    do_download,
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1376, in unpack_url
    self.session,
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 572, in unpack_http_url
    download_hash = _download_url(resp, link, temp_location)
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 433, in _download_url
    for chunk in resp_read(4096):
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 421, in resp_read
    chunk_size, decode_content=False):
  File "/usr/share/python-wheels/urllib3-1.7.1-py2.py3-none-any.whl/urllib3/response.py", line 225, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/usr/share/python-wheels/urllib3-1.7.1-py2.py3-none-any.whl/urllib3/response.py", line 174, in read
    data = self._fp.read(amt)
  File "/usr/lib/python2.7/httplib.py", line 573, in read
    s = self.fp.read(amt)
  File "/usr/lib/python2.7/socket.py", line 380, in read
    data = self._sock.recv(left)
  File "/usr/lib/python2.7/ssl.py", line 341, in recv
    return self.read(buflen)
  File "/usr/lib/python2.7/ssl.py", line 260, in read
    return self._sslobj.read(len)
SSLError: The read operation timed out

Storing debug log for failure in /home/sunshine/.pip/pip.log

**Comment by shidenggui** [comment]
需要 python3， python 2.7 有一点兼容性问题
